<a href="https://colab.research.google.com/github/omkarande2525/ML-Pracs/blob/main/OM_ASSIGNMENT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import os
os.listdir()

['.config', 'sample_data']

In [ ]:
from google .colab import files
uploaded = files.upload()

Saving data.csv to data.csv

In [ ]:
df = pd.read_csv("data.csv")
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

In [ ]:
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(4), int64(9), object(5)
memory usage: 647.0+ KB

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000

In [ ]:
students = pd.DataFrame({
    'Student_ID': [1,2,3,4,5,6,7,8,9,10],
    'Name': ['Om','Ram','Rohit','Prajakta','Rushi','Soham','Shree','Atharva','Swaraj','Abhi'],
    'Age': [20,21,20,22,21,20,21,22,20,21],
    'Gender': ['M','M','M','F','M','M','F','M','M','M'],
    'Department': ['CSE','IT','CSE','CSE','IT','CSE','IT','CSE','IT','CSE'],
    'Marks': [88,75,92,85,78,90,80,95,70,89],
    'Attendance': [92,85,95,88,80,90,87,96,75,91],
    'Internship': ['Yes','No','Yes','Yes','No','Yes','No','Yes','No','Yes']
})

In [ ]:
students

   Student_ID      Name  Age Gender Department  Marks  Attendance Internship
0           1        Om   20      M        CSE     88          92        Yes
1           2       Ram   21      M         IT     75          85         No
2           3     Rohit   20      M        CSE     92          95        Yes
3           4  Prajakta   22      F        CSE     85          88        Yes
4           5     Rushi   21      M         IT     78          80         No
5           6     Soham   20      M        CSE     90          90        Yes
6           7     Shree   21      F         IT     80          87         No
7           8   Atharva   22      M        CSE     95          96        Yes
8           9    Swaraj   20      M         IT     70          75         No
9          10      Abhi   21      M        CSE     89          91        Yes

In [ ]:
students.head()

   Student_ID      Name  Age Gender Department  Marks  Attendance Internship
0           1        Om   20      M        CSE     88          92        Yes
1           2       Ram   21      M         IT     75          85         No
2           3     Rohit   20      M        CSE     92          95        Yes
3           4  Prajakta   22      F        CSE     85          88        Yes
4           5     Rushi   21      M         IT     78          80         No

In [ ]:
students.index

RangeIndex(start=0, stop=10, step=1)

In [ ]:
students.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'Marks',
       'Attendance', 'Internship'],
      dtype='object')

In [ ]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000

In [ ]:
students.sort_index(axis=1, ascending=False)

   Student_ID      Name  Marks Internship Gender Department  Attendance  Age
0           1        Om     88        Yes      M        CSE          92   20
1           2       Ram     75         No      M         IT          85   21
2           3     Rohit     92        Yes      M        CSE          95   20
3           4  Prajakta     85        Yes      F        CSE          88   22
4           5     Rushi     78         No      M         IT          80   21
5           6     Soham     90        Yes      M        CSE          90   20
6           7     Shree     80         No      F         IT          87   21
7           8   Atharva     95        Yes      M        CSE          96   22
8           9    Swaraj     70         No      M         IT          75   20
9          10      Abhi     89        Yes      M        CSE          91   21

In [ ]:
students[0:4]

   Student_ID      Name  Age Gender Department  Marks  Attendance Internship
0           1        Om   20      M        CSE     88          92        Yes
1           2       Ram   21      M         IT     75          85         No
2           3     Rohit   20      M        CSE     92          95        Yes
3           4  Prajakta   22      F        CSE     85          88        Yes

In [ ]:
students.iloc[3]

Student_ID           4
Name          Prajakta
Age                 22
Gender               F
Department         CSE
Marks               85
Attendance          88
Internship         Yes
Name: 3, dtype: object

In [ ]:
students[students['Attendance'] > 90]

   Student_ID     Name  Age Gender Department  Marks  Attendance Internship
0           1       Om   20      M        CSE     88          92        Yes
2           3    Rohit   20      M        CSE     92          95        Yes
7           8  Atharva   22      M        CSE     95          96        Yes
9          10     Abhi   21      M        CSE     89          91        Yes

In [ ]:
students.isna()

   Student_ID   Name    Age  Gender  Department  Marks  Attendance  Internship
0       False  False  False   False       False  False       False       False
1       False  False  False   False       False  False       False       False
2       False  False  False   False       False  False       False       False
3       False  False  False   False       False  False       False       False
4       False  False  False   False       False  False       False       False
5       False  False  False   False       False  False       False       False
6       False  False  False   False       False  False       False       False
7       False  False  False   False       False  False       False       False
8       False  False  False   False       False  False       False       False
9       False  False  False   False       False  False       False       False

In [ ]:
students['Marks'].apply(lambda x: x + 2)

0    90
1    77
2    94
3    87
4    80
5    92
6    82
7    97
8    72
9    91
Name: Marks, dtype: int64

In [ ]:
students.iloc[3:7, 1:5]

       Name  Age Gender Department
3  Prajakta   22      F        CSE
4     Rushi   21      M         IT
5     Soham   20      M        CSE
6     Shree   21      F         IT

In [ ]:
students.mean(numeric_only=True)

Student_ID     5.5
Age           20.8
Marks         84.2
Attendance    87.9
dtype: float64

In [ ]:
students.groupby('Department')['Attendance'].mean()

Department
CSE    92.00
IT     81.75
Name: Attendance, dtype: float64

In [ ]:
students.sort_index()

   Student_ID      Name  Age Gender Department  Marks  Attendance Internship
0           1        Om   20      M        CSE     88          92        Yes
1           2       Ram   21      M         IT     75          85         No
2           3     Rohit   20      M        CSE     92          95        Yes
3           4  Prajakta   22      F        CSE     85          88        Yes
4           5     Rushi   21      M         IT     78          80         No
5           6     Soham   20      M        CSE     90          90        Yes
6           7     Shree   21      F         IT     80          87         No
7           8   Atharva   22      M        CSE     95          96        Yes
8           9    Swaraj   20      M         IT     70          75         No
9          10      Abhi   21      M        CSE     89          91        Yes

In [ ]:
students.tail()

   Student_ID     Name  Age Gender Department  Marks  Attendance Internship
5           6    Soham   20      M        CSE     90          90        Yes
6           7    Shree   21      F         IT     80          87         No
7           8  Atharva   22      M        CSE     95          96        Yes
8           9   Swaraj   20      M         IT     70          75         No
9          10     Abhi   21      M        CSE     89          91        Yes

In [ ]:
students.sample(5)

   Student_ID     Name  Age Gender Department  Marks  Attendance Internship
1           2      Ram   21      M         IT   75.0          85         No
7           8  Atharva   22      M        CSE   95.0          96        Yes
8           9   Swaraj   20      M         IT   70.0          75         No
2           3    Rohit   20      M        CSE   92.0          95        Yes
5           6    Soham   20      M        CSE   90.0          90        Yes

In [ ]:
students['Department'].value_counts()

Department
CSE    6
IT     4
Name: count, dtype: int64

In [ ]:
students['Department'].unique()

array(['CSE', 'IT'], dtype=object)

In [ ]:
students.drop('Internship', axis=1)

   Student_ID      Name  Age Gender Department  Marks  Attendance
0           1        Om   20      M        CSE   88.0          92
1           2       Ram   21      M         IT   75.0          85
2           3     Rohit   20      M        CSE   92.0          95
3           4  Prajakta   22      F        CSE   85.0          88
4           5     Rushi   21      M         IT   78.0          80
5           6     Soham   20      M        CSE   90.0          90
6           7     Shree   21      F         IT   80.0          87
7           8   Atharva   22      M        CSE   95.0          96
8           9    Swaraj   20      M         IT   70.0          75
9          10      Abhi   21      M        CSE   89.0          91

In [ ]:
students.rename(columns={'Marks': 'Total_Marks'})

,Student_ID,Name,Age,Gender,Department,Total_Marks,Attendance,Internship
0,1,Om,20,M,CSE,88.0,92,Yes
1,2,Ram,21,M,IT,75.0,85,No
2,3,Rohit,20,M,CSE,92.0,95,Yes
3,4,Prajakta,22,F,CSE,85.0,88,Yes
4,5,Rushi,21,M,IT,78.0,80,No
5,6,Soham,20,M,CSE,90.0,90,Yes
6,7,Shree,21,F,IT,80.0,87,No
7,8,Atharva,22,M,CSE,95.0,96,Yes
8,9,Swaraj,20,M,IT,70.0,75,No
9,10,Abhi,21,M,CSE,89.0,91,Yes

In [ ]:
students['Marks'] = students['Marks'].astype(float)

In [ ]:
students.fillna(0)

   Student_ID      Name  Age Gender Department  Marks  Attendance Internship
0           1        Om   20      M        CSE     88          92        Yes
1           2       Ram   21      M         IT     75          85         No
2           3     Rohit   20      M        CSE     92          95        Yes
3           4  Prajakta   22      F        CSE     85          88        Yes
4           5     Rushi   21      M         IT     78          80         No
5           6     Soham   20      M        CSE     90          90        Yes
6           7     Shree   21      F         IT     80          87         No
7           8   Atharva   22      M        CSE     95          96        Yes
8           9    Swaraj   20      M         IT     70          75         No
9          10      Abhi   21      M        CSE     89          91        Yes

In [ ]:
extra = students.iloc[0:2]
pd.concat([students, extra])

   Student_ID      Name  Age Gender Department  Marks  Attendance Internship
0           1        Om   20      M        CSE     88          92        Yes
1           2       Ram   21      M         IT     75          85         No
2           3     Rohit   20      M        CSE     92          95        Yes
3           4  Prajakta   22      F        CSE     85          88        Yes
4           5     Rushi   21      M         IT     78          80         No
5           6     Soham   20      M        CSE     90          90        Yes
6           7     Shree   21      F         IT     80          87         No
7           8   Atharva   22      M        CSE     95          96        Yes
8           9    Swaraj   20      M         IT     70          75         No
9          10      Abhi   21      M        CSE     89          91        Yes
0           1        Om   20      M        CSE     88          92        Yes
1           2       Ram   21      M         IT     75          85         No

In [ ]:
dept = pd.DataFrame({
    'Department': ['CSE', 'IT'],
    'HOD': ['Dr. Sharma', 'Dr. Patil']
})

pd.merge(students, dept, on='Department')

,Student_ID,Name,Age,Gender,Department,Marks,Attendance,Internship,HOD
0,1,Om,20,M,CSE,88,92,Yes,Dr. Sharma
1,2,Ram,21,M,IT,75,85,No,Dr. Patil
2,3,Rohit,20,M,CSE,92,95,Yes,Dr. Sharma
3,4,Prajakta,22,F,CSE,85,88,Yes,Dr. Sharma
4,5,Rushi,21,M,IT,78,80,No,Dr. Patil
5,6,Soham,20,M,CSE,90,90,Yes,Dr. Sharma
6,7,Shree,21,F,IT,80,87,No,Dr. Patil
7,8,Atharva,22,M,CSE,95,96,Yes,Dr. Sharma
8,9,Swaraj,20,M,IT,70,75,No,Dr. Patil
9,10,Abhi,21,M,CSE,89,91,Yes,Dr. Sharma